# Generated by Django 2.1.3 on 2019-05-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('details', models.TextField()),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
    ]
