# Generated by Django 2.1.3 on 2019-05-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prize',
            field=models.IntegerField(default=45),
            preserve_default=False,
        ),
    ]
